error: Introduce error codes
Introduce a common place for error codes. Functions should all return 0
for success or a negative integer error code when something goes wrong.
We will mostly follow Linux standard error codes where it makes sense,
but free to expand as needed.